-- =============================================================================
-- Lakehouse Parameter Configuration Table
-- =============================================================================
-- This script creates a Delta table for storing parameter values used by
-- the paginated report batch executor notebook.
--
-- Usage:
--   1. Run this script in a Fabric Lakehouse notebook
--   2. Insert parameter values using the sample_data.sql script
--   3. Configure the executor notebook to use 'lakehouse' as the parameter source
--
-- Author: Generated by Claude Code
-- Version: 1.0
-- =============================================================================

CREATE TABLE IF NOT EXISTS parameter_config (
    -- Primary key
    ParameterID BIGINT GENERATED ALWAYS AS IDENTITY,

    -- Parameter identification
    Category STRING NOT NULL COMMENT 'Category or group (e.g., CustomerList, RegionList)',
    ParameterName STRING NOT NULL COMMENT 'Descriptive name for the parameter',
    ParameterValue STRING NOT NULL COMMENT 'The actual parameter value to use',
    Description STRING COMMENT 'User-friendly description',

    -- Status and ordering
    IsActive BOOLEAN NOT NULL DEFAULT true COMMENT 'Enable/disable without deleting',
    SortOrder INT NOT NULL DEFAULT 0 COMMENT 'Control execution order',

    -- Metadata
    CreatedBy STRING COMMENT 'User or process that created this entry',
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT 'Creation timestamp',
    ModifiedBy STRING COMMENT 'User or process that last modified this entry',
    ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT 'Last modification timestamp',

    -- Optional security (for manual filtering)
    AllowedUsers STRING COMMENT 'Comma-separated list of emails who can use this parameter',
    AllowedGroups STRING COMMENT 'Comma-separated list of AD groups who can use this parameter',

    -- Optional scheduling
    ValidFrom TIMESTAMP COMMENT 'Start date for parameter validity',
    ValidTo TIMESTAMP COMMENT 'End date for parameter validity',

    -- Custom metadata (JSON string for flexibility)
    Metadata STRING COMMENT 'Additional metadata in JSON format',

    -- Constraints
    CONSTRAINT pk_parameter_config PRIMARY KEY (ParameterID)
)
USING DELTA
PARTITIONED BY (Category)
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
);

-- =============================================================================
-- Create indexes for better query performance
-- =============================================================================

-- Index for common query patterns
CREATE INDEX IF NOT EXISTS idx_category_active
ON parameter_config (Category, IsActive);

CREATE INDEX IF NOT EXISTS idx_active_sortorder
ON parameter_config (IsActive, SortOrder);

-- =============================================================================
-- Create view for easy access to active parameters only
-- =============================================================================

CREATE OR REPLACE VIEW active_parameters AS
SELECT
    ParameterID,
    Category,
    ParameterName,
    ParameterValue,
    Description,
    SortOrder,
    CreatedDate,
    ModifiedDate,
    ValidFrom,
    ValidTo
FROM parameter_config
WHERE IsActive = true
  AND (ValidFrom IS NULL OR ValidFrom <= CURRENT_TIMESTAMP())
  AND (ValidTo IS NULL OR ValidTo >= CURRENT_TIMESTAMP())
ORDER BY Category, SortOrder, ParameterName;

-- =============================================================================
-- Sample queries for reference
-- =============================================================================

-- Query 1: Get all active parameters for a category
-- SELECT ParameterValue
-- FROM parameter_config
-- WHERE Category = 'CustomerList' AND IsActive = true
-- ORDER BY SortOrder;

-- Query 2: Get parameters with date range filtering
-- SELECT ParameterValue
-- FROM active_parameters
-- WHERE Category = 'ReportSchedule';

-- Query 3: Get all categories
-- SELECT DISTINCT Category, COUNT(*) as ParameterCount
-- FROM parameter_config
-- WHERE IsActive = true
-- GROUP BY Category
-- ORDER BY Category;

-- Query 4: Get parameter statistics
-- SELECT
--     Category,
--     COUNT(*) as Total,
--     SUM(CASE WHEN IsActive THEN 1 ELSE 0 END) as Active,
--     SUM(CASE WHEN IsActive THEN 0 ELSE 1 END) as Inactive
-- FROM parameter_config
-- GROUP BY Category
-- ORDER BY Category;

PRINT('✓ Parameter configuration table created successfully');
PRINT('  Table: parameter_config');
PRINT('  View: active_parameters');
PRINT('  Partitioned by: Category');
PRINT('  Indexes: idx_category_active, idx_active_sortorder');
PRINT('');
PRINT('Next steps:');
PRINT('  1. Run sample_data.sql to insert test data');
PRINT('  2. Configure executor notebook with:');
PRINT('     - special_values_source = "lakehouse"');
PRINT('     - lakehouse_table = "parameter_config"');
PRINT('     - lakehouse_category = "YourCategory"');
