-- =============================================================================
-- Sample Parameter Data for Testing
-- =============================================================================
-- This script inserts sample parameter data into the parameter_config table
-- for testing the paginated report batch executor.
--
-- Usage:
--   1. Ensure create_lakehouse_parameter_table.sql has been run first
--   2. Run this script to insert sample data
--   3. Test the executor notebook with these sample parameters
--
-- Author: Generated by Claude Code
-- Version: 1.0
-- =============================================================================

-- Clear existing sample data (optional - comment out if you want to keep existing data)
-- DELETE FROM parameter_config WHERE CreatedBy = 'Sample Data Script';

-- =============================================================================
-- Sample 1: Customer List for Monthly Reports
-- =============================================================================

INSERT INTO parameter_config (
    Category, ParameterName, ParameterValue, Description,
    IsActive, SortOrder, CreatedBy
)
VALUES
    ('MonthlyReportCustomers', 'Acme Corporation', 'Acme Corp', 'Large enterprise customer', true, 1, 'Sample Data Script'),
    ('MonthlyReportCustomers', 'TechStart Inc', 'TechStart Inc', 'Technology startup', true, 2, 'Sample Data Script'),
    ('MonthlyReportCustomers', 'Global Solutions Ltd', 'Global Solutions', 'International consulting firm', true, 3, 'Sample Data Script'),
    ('MonthlyReportCustomers', 'Innovation Labs', 'Innovation Labs', 'R&D focused company', true, 4, 'Sample Data Script'),
    ('MonthlyReportCustomers', 'Metro Retail Group', 'Metro Retail', 'Retail chain', true, 5, 'Sample Data Script');

-- =============================================================================
-- Sample 2: Regional Distribution Lists
-- =============================================================================

INSERT INTO parameter_config (
    Category, ParameterName, ParameterValue, Description,
    IsActive, SortOrder, CreatedBy
)
VALUES
    ('RegionList', 'North America', 'North America', 'US and Canada region', true, 1, 'Sample Data Script'),
    ('RegionList', 'Europe', 'Europe', 'European region', true, 2, 'Sample Data Script'),
    ('RegionList', 'Asia Pacific', 'Asia Pacific', 'APAC region', true, 3, 'Sample Data Script'),
    ('RegionList', 'Latin America', 'Latin America', 'LATAM region', true, 4, 'Sample Data Script'),
    ('RegionList', 'Middle East & Africa', 'MEA', 'MEA region', true, 5, 'Sample Data Script');

-- =============================================================================
-- Sample 3: Department Report Distribution
-- =============================================================================

INSERT INTO parameter_config (
    Category, ParameterName, ParameterValue, Description,
    IsActive, SortOrder, CreatedBy
)
VALUES
    ('DepartmentList', 'Sales', 'Sales', 'Sales department', true, 1, 'Sample Data Script'),
    ('DepartmentList', 'Marketing', 'Marketing', 'Marketing department', true, 2, 'Sample Data Script'),
    ('DepartmentList', 'Finance', 'Finance', 'Finance department', true, 3, 'Sample Data Script'),
    ('DepartmentList', 'Operations', 'Operations', 'Operations department', true, 4, 'Sample Data Script'),
    ('DepartmentList', 'IT', 'IT', 'IT department', true, 5, 'Sample Data Script');

-- =============================================================================
-- Sample 4: Year Parameters for Historical Reports
-- =============================================================================

INSERT INTO parameter_config (
    Category, ParameterName, ParameterValue, Description,
    IsActive, SortOrder, CreatedBy
)
VALUES
    ('FiscalYearList', 'FY 2022', '2022', 'Fiscal year 2022', true, 1, 'Sample Data Script'),
    ('FiscalYearList', 'FY 2023', '2023', 'Fiscal year 2023', true, 2, 'Sample Data Script'),
    ('FiscalYearList', 'FY 2024', '2024', 'Fiscal year 2024', true, 3, 'Sample Data Script'),
    ('FiscalYearList', 'FY 2025', '2025', 'Fiscal year 2025', true, 4, 'Sample Data Script');

-- =============================================================================
-- Sample 5: Product Categories
-- =============================================================================

INSERT INTO parameter_config (
    Category, ParameterName, ParameterValue, Description,
    IsActive, SortOrder, CreatedBy
)
VALUES
    ('ProductCategoryList', 'Electronics', 'Electronics', 'Electronic products', true, 1, 'Sample Data Script'),
    ('ProductCategoryList', 'Apparel', 'Apparel', 'Clothing and accessories', true, 2, 'Sample Data Script'),
    ('ProductCategoryList', 'Home & Garden', 'Home & Garden', 'Home improvement and gardening', true, 3, 'Sample Data Script'),
    ('ProductCategoryList', 'Sports & Outdoors', 'Sports & Outdoors', 'Sporting goods', true, 4, 'Sample Data Script'),
    ('ProductCategoryList', 'Books & Media', 'Books & Media', 'Books, movies, music', true, 5, 'Sample Data Script');

-- =============================================================================
-- Sample 6: Test Data with Inactive Parameters
-- =============================================================================

INSERT INTO parameter_config (
    Category, ParameterName, ParameterValue, Description,
    IsActive, SortOrder, CreatedBy
)
VALUES
    ('TestCategory', 'Active Test 1', 'Test1', 'Active test parameter', true, 1, 'Sample Data Script'),
    ('TestCategory', 'Active Test 2', 'Test2', 'Active test parameter', true, 2, 'Sample Data Script'),
    ('TestCategory', 'Inactive Test 3', 'Test3', 'Inactive test parameter', false, 3, 'Sample Data Script');

-- =============================================================================
-- Sample 7: Parameters with Date Validity
-- =============================================================================

INSERT INTO parameter_config (
    Category, ParameterName, ParameterValue, Description,
    IsActive, SortOrder, CreatedBy, ValidFrom, ValidTo
)
VALUES
    ('SeasonalReports', 'Q1 2025 Report', 'Q1_2025', 'First quarter 2025', true, 1, 'Sample Data Script', '2025-01-01', '2025-03-31'),
    ('SeasonalReports', 'Q2 2025 Report', 'Q2_2025', 'Second quarter 2025', true, 2, 'Sample Data Script', '2025-04-01', '2025-06-30'),
    ('SeasonalReports', 'Q3 2025 Report', 'Q3_2025', 'Third quarter 2025', true, 3, 'Sample Data Script', '2025-07-01', '2025-09-30'),
    ('SeasonalReports', 'Q4 2025 Report', 'Q4_2025', 'Fourth quarter 2025', true, 4, 'Sample Data Script', '2025-10-01', '2025-12-31');

-- =============================================================================
-- Verification Queries
-- =============================================================================

PRINT('✓ Sample data inserted successfully');
PRINT('');

-- Show inserted counts
SELECT
    Category,
    COUNT(*) as TotalCount,
    SUM(CASE WHEN IsActive THEN 1 ELSE 0 END) as ActiveCount
FROM parameter_config
WHERE CreatedBy = 'Sample Data Script'
GROUP BY Category
ORDER BY Category;

PRINT('');
PRINT('Sample usage in executor notebook:');
PRINT('  1. For customers: lakehouse_category = "MonthlyReportCustomers"');
PRINT('  2. For regions: lakehouse_category = "RegionList"');
PRINT('  3. For departments: lakehouse_category = "DepartmentList"');
PRINT('  4. For years: lakehouse_category = "FiscalYearList"');
PRINT('  5. For products: lakehouse_category = "ProductCategoryList"');
PRINT('');

-- Show sample active parameters
PRINT('Sample query - Active customers:');
SELECT ParameterValue, Description
FROM parameter_config
WHERE Category = 'MonthlyReportCustomers'
  AND IsActive = true
ORDER BY SortOrder
LIMIT 3;
