/*
==============================================================================
Sample DAX Queries for Semantic Model Parameter Extraction
==============================================================================

This file contains sample DAX queries for extracting parameter values from
Power BI/Fabric semantic models to use with the paginated report batch executor.

Usage:
  1. Identify the semantic model that contains your parameter data
  2. Modify the table and column names to match your semantic model
  3. Copy the appropriate query to the semantic_model_dax_query notebook parameter
  4. Configure the executor notebook with:
     - special_values_source = "semantic_model"
     - semantic_model_workspace_id = "your-workspace-guid"
     - semantic_model_dataset_id = "your-dataset-guid"
     - semantic_model_dax_query = "your-dax-query"

Author: Generated by Claude Code
Version: 1.0
==============================================================================
*/

-- =============================================================================
-- EXAMPLE 1: Get All Distinct Customers
-- =============================================================================
-- Use Case: Generate a report for each customer in the system
-- Semantic Model: Sales Analytics
-- Table: DimCustomer
-- Column: CustomerName

EVALUATE
DISTINCT('DimCustomer'[CustomerName])
ORDER BY 'DimCustomer'[CustomerName]


-- =============================================================================
-- EXAMPLE 2: Get Active Customers Only
-- =============================================================================
-- Use Case: Generate reports only for active customers
-- Filter: Only customers with IsActive = TRUE

EVALUATE
FILTER(
    DISTINCT('DimCustomer'[CustomerName]),
    'DimCustomer'[IsActive] = TRUE
)
ORDER BY 'DimCustomer'[CustomerName]


-- =============================================================================
-- EXAMPLE 3: Get Top N Customers by Sales
-- =============================================================================
-- Use Case: Generate reports for top 10 customers by sales amount
-- Tables: DimCustomer, FactSales

EVALUATE
TOPN(
    10,
    SUMMARIZECOLUMNS(
        'DimCustomer'[CustomerName],
        "TotalSales", SUM('FactSales'[SalesAmount])
    ),
    [TotalSales], DESC
)


-- =============================================================================
-- EXAMPLE 4: Get All Regions
-- =============================================================================
-- Use Case: Generate regional reports
-- Table: DimGeography
-- Column: Region

EVALUATE
DISTINCT('DimGeography'[Region])
ORDER BY 'DimGeography'[Region]


-- =============================================================================
-- EXAMPLE 5: Get Regions with Sales Above Threshold
-- =============================================================================
-- Use Case: Only generate reports for regions with significant sales
-- Filter: Regions with sales > $1,000,000

EVALUATE
FILTER(
    SUMMARIZECOLUMNS(
        'DimGeography'[Region],
        "TotalSales", SUM('FactSales'[SalesAmount])
    ),
    [TotalSales] > 1000000
)
ORDER BY 'DimGeography'[Region]


-- =============================================================================
-- EXAMPLE 6: Get Customers with Sales in Last 12 Months
-- =============================================================================
-- Use Case: Generate reports for customers with recent activity
-- Time Filter: Last 12 months from today

EVALUATE
CALCULATETABLE(
    DISTINCT('DimCustomer'[CustomerName]),
    DATESINPERIOD(
        'DimDate'[Date],
        TODAY(),
        -12,
        MONTH
    )
)
ORDER BY 'DimCustomer'[CustomerName]


-- =============================================================================
-- EXAMPLE 7: Get Customer-Region Combinations
-- =============================================================================
-- Use Case: Generate report for each customer in each region
-- Result: Multiple columns (will use first column as parameter value)
-- Note: For multi-parameter loops, you'll need to parse the result differently

EVALUATE
SUMMARIZECOLUMNS(
    'DimCustomer'[CustomerName],
    'DimGeography'[Region]
)
ORDER BY 'DimCustomer'[CustomerName], 'DimGeography'[Region]


-- =============================================================================
-- EXAMPLE 8: Get Fiscal Years
-- =============================================================================
-- Use Case: Generate historical reports for each fiscal year
-- Table: DimDate
-- Column: FiscalYear

EVALUATE
DISTINCT('DimDate'[FiscalYear])
ORDER BY 'DimDate'[FiscalYear] DESC


-- =============================================================================
-- EXAMPLE 9: Get Product Categories with Active Products
-- =============================================================================
-- Use Case: Generate category reports only if category has active products
-- Tables: DimProduct
-- Columns: Category, IsActive

EVALUATE
DISTINCT(
    SELECTCOLUMNS(
        FILTER(
            'DimProduct',
            'DimProduct'[IsActive] = TRUE
        ),
        "Category", 'DimProduct'[Category]
    )
)
ORDER BY [Category]


-- =============================================================================
-- EXAMPLE 10: Get Sales Representatives with Territory
-- =============================================================================
-- Use Case: Generate personalized reports for sales reps
-- Tables: DimEmployee, DimTerritory

EVALUATE
SUMMARIZECOLUMNS(
    'DimEmployee'[EmployeeName],
    'DimTerritory'[TerritoryName]
)
ORDER BY 'DimEmployee'[EmployeeName]


-- =============================================================================
-- EXAMPLE 11: Get Customers by Segment
-- =============================================================================
-- Use Case: Generate reports for enterprise customers only
-- Filter: CustomerSegment = "Enterprise"

EVALUATE
FILTER(
    DISTINCT('DimCustomer'[CustomerName]),
    'DimCustomer'[CustomerSegment] = "Enterprise"
)
ORDER BY 'DimCustomer'[CustomerName]


-- =============================================================================
-- EXAMPLE 12: Get Parameters with Custom Formatting
-- =============================================================================
-- Use Case: Need to format parameter values differently
-- Example: Combine multiple columns into one parameter value

EVALUATE
DISTINCT(
    SELECTCOLUMNS(
        'DimCustomer',
        "CustomerCode",
        'DimCustomer'[CustomerID] & " - " & 'DimCustomer'[CustomerName]
    )
)
ORDER BY [CustomerCode]


-- =============================================================================
-- EXAMPLE 13: Get Time Periods for Recurring Reports
-- =============================================================================
-- Use Case: Generate monthly reports for last 6 months
-- Result: Returns date values that can be used as parameters

EVALUATE
DISTINCT(
    SELECTCOLUMNS(
        FILTER(
            'DimDate',
            'DimDate'[Date] >= DATE(YEAR(TODAY()), MONTH(TODAY()) - 6, 1)
            && 'DimDate'[Date] < DATE(YEAR(TODAY()), MONTH(TODAY()), 1)
        ),
        "MonthYear", FORMAT('DimDate'[Date], "YYYY-MM")
    )
)
ORDER BY [MonthYear]


-- =============================================================================
-- EXAMPLE 14: Get Values with Row-Level Security Applied
-- =============================================================================
-- Use Case: Different users see different parameter values based on RLS
-- Note: RLS is automatically applied when querying via sempy
-- This query respects the current user's security context

EVALUATE
DISTINCT('DimCustomer'[CustomerName])
-- RLS will filter this automatically based on user permissions


-- =============================================================================
-- EXAMPLE 15: Complex Filter with Multiple Conditions
-- =============================================================================
-- Use Case: Generate reports with multiple business rules
-- Conditions:
--   - Active customers
--   - With sales > $50,000 in last year
--   - In specific regions

EVALUATE
FILTER(
    SUMMARIZECOLUMNS(
        'DimCustomer'[CustomerName],
        FILTER(
            'DimDate',
            'DimDate'[Date] >= DATE(YEAR(TODAY()) - 1, 1, 1)
        ),
        FILTER(
            'DimGeography',
            'DimGeography'[Region] IN {"North America", "Europe"}
        ),
        "TotalSales", SUM('FactSales'[SalesAmount])
    ),
    [TotalSales] > 50000
    && RELATED('DimCustomer'[IsActive]) = TRUE
)
ORDER BY [TotalSales] DESC


-- =============================================================================
-- EXAMPLE 16: Get All Measures (for Metric-Based Reports)
-- =============================================================================
-- Use Case: Generate a report for each measure/metric
-- Note: This uses INFO functions (may not work in all environments)

EVALUATE
SELECTCOLUMNS(
    FILTER(
        INFO.MEASURES(),
        NOT(CONTAINSSTRING([Name], "Hidden"))
    ),
    "MeasureName", [Name]
)
ORDER BY [MeasureName]


-- =============================================================================
-- TIPS FOR WRITING EFFECTIVE DAX QUERIES
-- =============================================================================

/*
1. ALWAYS use EVALUATE statement - required for DAX queries

2. DISTINCT is your friend - removes duplicates
   EVALUATE DISTINCT('Table'[Column])

3. Use FILTER for conditions
   FILTER(DISTINCT('Table'[Column]), 'Table'[IsActive] = TRUE)

4. Use ORDER BY for predictable ordering
   ORDER BY 'Table'[Column] ASC/DESC

5. First column is used as parameter value
   - If query returns multiple columns, only first column is used
   - Use SELECTCOLUMNS to choose which column to return first

6. Row-Level Security (RLS) is automatically applied
   - Query results respect current user's permissions
   - No need for additional security filters

7. Test queries in Power BI Desktop first
   - Connect to your semantic model
   - Use DAX Studio or Performance Analyzer
   - Verify results before using in notebook

8. Consider performance
   - Use DISTINCT instead of VALUES when appropriate
   - Avoid COUNTROWS if not needed
   - Test with realistic data volumes

9. Handle NULL values
   - DAX might return blanks
   - Notebook will filter out NULL values automatically

10. Use measures when available
    - Leverages existing business logic
    - Consistent with reports users see
*/

-- =============================================================================
-- COMMON PATTERNS CHEAT SHEET
-- =============================================================================

/*
-- Get distinct values:
EVALUATE DISTINCT('Table'[Column])

-- Get filtered values:
EVALUATE FILTER(DISTINCT('Table'[Column]), 'Table'[Status] = "Active")

-- Get top N:
EVALUATE TOPN(10, 'Table', 'Table'[SortColumn], DESC)

-- Get values from date range:
EVALUATE CALCULATETABLE(
    DISTINCT('Table'[Column]),
    DATESBETWEEN('Date'[Date], DATE(2024,1,1), DATE(2024,12,31))
)

-- Get combinations:
EVALUATE SUMMARIZECOLUMNS('Table1'[Column1], 'Table2'[Column2])

-- Get with calculation:
EVALUATE
SUMMARIZECOLUMNS(
    'Table'[Column],
    "Metric", SUM('FactTable'[Amount])
)

-- Format output:
EVALUATE
SELECTCOLUMNS(
    'Table',
    "FormattedValue", FORMAT('Table'[Column], "Custom Format")
)
*/
